=== daangn/karrotframe/packages/pathfinder/src/constant/validator.json
{
  "$id": "@karrotframe/pathfinder",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "validator for json schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "endpoint": {
      "type": "string"
    },
    "endpoints": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "version": {
      "type": "number"
    },
    "routes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "path": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        },
        "additionalProperties": {
          "type": "object"
        },
        "required": ["name", "path"]
      }
    }
  },
  "required": ["name", "version", "routes"],
  "oneOf": [
    {
      "required": ["endpoint"]
    },
    {
      "required": ["endpoints"]
    }
  ]
}

=== daangn/karrotframe/packages/pathfinder/example/schema.json
{
  "name": "example",
  "description": "sdk for example route",
  "author": "John Doe",
  "endpoint": "https://example.com",
  "endpoints": {
    "prod": "https://example.prod.com"
  },
  "version": 1,
  "routes": [
    {
      "name": "guitar",
      "path": "/product/guitar/:guitarId",
      "description": "Method to open guitar detail page",
      "queryParams": {
        "additionalProperties": false
      }
    },
    {
      "name": "accessory",
      "path": "/product/accessory/:accessoryId",
      "description": "Method to open accessory detail page",
      "queryParams": {
        "type": "object",
        "properties": {
          "referrer": {
            "type": "string",
            "description": "tracking referrer page",
            "enum": ["guitar"]
          }
        },
        "required": ["referrer"],
        "additionalProperties": false
      }
    }
  ]
}
